spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coworking_space_reservation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  servlet:
    session:
      timeout: 600

db:
  init:
    db:
      url: jdbc:postgresql://localhost:5432/
      name: postgres
  new:
    db:
      name: coworking_space_reservation
  user: postgres
  password: postgres
